version: '3.8'


services:
  inventory-db:
    build: ./services/inventory-db
    image: inventory-db:v1
    container_name: inventory-db
    env_file:
      - ./services/inventory-db/.env
    volumes:
      - inventory-db:/var/lib/postgresql/data
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  billing-db:
    build: ./services/billing-db
    image: billing-db:v1
    container_name: billing-db
    env_file:
      - ./services/billing-db/.env
    volumes:
      - billing-db:/var/lib/postgresql/data
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  inventory-app:
    build: ./services/inventory-app
    image: inventory-app:v1
    container_name: inventory-app
    env_file:
      - ./services/inventory-app/.env
    ports:
      - "8080:8080"
    depends_on:
      inventory-db:
        condition: service_healthy
    networks:
      - my-network


  billing-app:
    build: ./services/billing-app
    image: billing-app:v1
    container_name: billing-app
    env_file:
      - ./services/billing-app/.env
    depends_on:
      billing-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - my-network


  rabbitmq:
    build: ./services/rabbitmq
    image: rabbitmq:v1
    container_name: rabbitmq
    env_file:
      - ./services/rabbitmq/.env
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5


  api-gateway-app:
    build: ./services/api-gateway-app
    image: api-gateway-app:v1
    container_name: api-gateway-app
    env_file:
      - ./services/api-gateway-app/.env
    volumes:
      - api-gateway-app:/var/lib/api/data
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      billing-app:
        condition: service_started
      inventory-app:
        condition: service_started
    networks:
      - my-network
  

  frontend-app:
    build: ./services/frontend-app
    image: frontend-app:v1
    container_name: frontend-app
    env_file:
      - ./services/frontend-app/.env
    ports:
      - "8501:8501"
    depends_on:
      api-gateway-app:
        condition: service_started
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s



networks:
  my-network:
    driver: bridge



volumes:
  inventory-db:
  billing-db:
  api-gateway-app:
  